### PR TITLE
Add latest posts feature for CoverPage (Closes: #9)

### PR DESCRIPTION
**Pull request by Moppa5**
**Description**
Add some practical coverpage functionality based on #9. This PR also adds the refresh option on coverpage and error handling on the case that no posts are found etc. 

**Note about changes**
Since this doesn't just add a component / feature, I wanted to give a little note / changelog on what have been changed too
- Give id "application" to ApplicationWindow. Can be accessed now from other pages too
- Copy the XMLHttp request required properties as global properties on ApplicationWindow
- Add a function which updates the local page data after reload to global data
- Add a function fetchLatestPosts() on ApplicationWindow which CoverPage uses to fetch data

If we want to move the whole XMLHttp request stuff on to the ApplicationWindow, I think this should be done in further improvements later. I didn't want to modify our current implementation too much since there's quite lot refactoring considering the pageStack.push operations that pass the data when moving another page. A good thing now is that more application related data is available globally on other pages too by using the id "application".

**Screenshots**
viewImage

I tested on my Xperia XA2 and the coverpage runs smoothly.

### CODE REVIEW

**Comment by szopin** [comment]
Great job, just one question: xml? (will check tomorrow in detail, just when did we move from json to xml???)

On Sunday, 2 August 2020, Santeri wrote:
> **Description**
> Add some practical coverpage functionality based on #9. This PR also adds the refresh option on coverpage and error handling on the case that no posts are found etc. 
> 
> **Note about changes**
> Since this doesn&#39;t just add a component / feature, I wanted to give a little note / changelog on what have been changed too
> - Give id &quot;application&quot; to ApplicationWindow. Can be accessed now from other pages too
> - Copy the XML request required properties as global properties on ApplicationWindow
> - Add a function which updates the local page data after reload to global data
> - Add a function fetchLatestPosts() on ApplicationWindow which CoverPage uses to fetch data
> 
> If we want to move the whole XML request stuff on to the ApplicationWindow, I think this should be done in further improvements later. I didn&#39;t want to modify our current implementation too much since there&#39;s quite lot refactoring considering the pageStack.push operations that pass the data when moving another page. A good thing now is that more application related data is available globally on other pages too by using the id &quot;application&quot;.
> 
> **Screenshots**
> viewImage
> 
> I tested on my Xperia XA2 and the coverpage runs smoothly. 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/szopin/harbour-sfos-forum-viewer/pull/10
> 
> -- Commit Summary --
> 
>   * Show some latest posts on coverpage
>   * Add refresh interaction for CoverPage
> 
> -- File Changes --
> 
>     M qml/cover/CoverPage.qml (59)
>     M qml/harbour-sfos-forum-viewer.qml (51)
>     M qml/pages/FirstPage.qml (30)
> 
> -- Patch Links --
> 
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/10.patch
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/10.diff
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/10
>

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin We never moved from json to xml :). What I meant by XML requests here is the JSON XMLHttprequest that they use. Nevertheless, I think it's a good thing to review before publishing a new version.

**Comment by szopin** [comment]
Oh ok, sorry, thought you found a way to force discourse speak xml somehow (which for me is 1000x more user friendly than parsing jsons), shame, will check tomorrow, thanks!

On Sunday, 2 August 2020, Santeri wrote:
> @szopin We never moved from json to xml :). What I meant by XML requests here is the JSON XMLHttprequest that they use. Nevertheless, I think it's a good thing to review before publishing a new version. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/10#issuecomment-66772236

-- 
Sent from my Jolla

**Comment by szopin** [comment]
It doesn't seem to work as expected... go to 'top' and cover displays properly the top posts while still claiming latest?

**Comment by Moppa5** [comment]
@szopin, CoverPage showing "Latest posts" was intended since the feature was about showing the latest posts in the current category. I agree that this might cause some confusion. If you want to change that, please amend them to my last commit.

**Comment by szopin** [comment]
Yeah working on it, latest posts just doesn't make sense as it's pulling whatever the latest pull was, so category view, top is also there, I'm just gonna rename it generic SFOS Forum and let it be for now, definitely needs more tweaking and testing

**Comment by szopin** [comment]
Ok, don't have much more time so just pushed it but one obvious bug is: if you go 'load more' the cover stays with the more loaded content even after refresh, if you could fix it would be really appreciated, thanks!

**Comment by Moppa5** [comment]
@szopin, Might take a look at this later today or tomorrow not sure how much I have time either. I think the cover XMLHttprequest could be implemented without the pageno property so that it downloads only the first page the most recent ones.

**Comment by szopin** [comment]
> could be implemented without the pageno property so that it downloads only the first page the most recent ones.
Nah, we need pageno to be able to 'load more' threads, unless you mean separate function just for coverpage, then do what you need, might need total decoupling or refactoring so same function is called from coverpage with an argument (forcover=1 or something), just make sure you test it thouroughly

>Oh and btw, I took a look at the newest version on which you had modified the CoverPage and it seems that 10 items is too many if users have more than 4 apps in multitasking view
Use the option in emulator to emulate also Xperias and tablet, the way it's overflowing now works for all, previously for xperias you would only cover top half of the cover, I'm fine with text behind the reload icon, makes more sense and even fulfills some function, we might need to tweak it to more than 10 if higher resolution devices come in, but for now seems to work fine on all?

**Comment by Moppa5** [comment]
> Nah, we need pageno to be able to 'load more' threads, unless you mean separate function just for coverpage, then do what you need, might need total decoupling or refactoring so same function is called from coverpage with an argument (forcover=1 or something), just make sure you test it thouroughly
> 
Need to check it out. The main point however was to not to show any more pages for coverpage so that shows the "latest" newest on the current category. 

> Use the option in emulator to emulate also Xperias and tablet, the way it's overflowing now works for all, previously for xperias you would only cover top half of the cover, I'm fine with text behind the reload icon, makes more sense and even fulfills some function, we might need to tweak it to more than 10 if higher resolution devices come in, but for now seems to work fine on all?

I simply don't understand that how it makes more sense and fulfills some function when it just simply looks bad. The function that it needs to fulfill is to have some latest posts, the count of the posts is not the key. There's no point having the coverpage full of text as the readability is much worse.

**Comment by szopin** [comment]
1. You're reusing a function and it has the  'extra' effect of bug explained

2. You don't understand me, different dpi/resolutions means your tweak only covered half of the cover on xperia x(+), just use the emulator to see what your changes do to all devices (like tablets), on jollaC 4 was fine, but on xperia x totally not (padding was reduced because why display empty space when ppl want content)
 
On Monday, 3 August 2020, Santeri wrote:
> > Nah, we need pageno to be able to 'load more' threads, unless you mean separate function just for coverpage, then do what you need, might need total decoupling or refactoring so same function is called from coverpage with an argument (forcover=1 or something), just make sure you test it thouroughly
> > 
> Need to check it out. The main point however was to not to show any more pages for coverpage so that shows the "latest" newest on the current category. 
> 
> > Use the option in emulator to emulate also Xperias and tablet, the way it's overflowing now works for all, previously for xperias you would only cover top half of the cover, I'm fine with text behind the reload icon, makes more sense and even fulfills some function, we might need to tweak it to more than 10 if higher resolution devices come in, but for now seems to work fine on all?
> 
> I simply don't understand that how it makes more sense and fulfills some function when it just simply looks bad. The function that it needs to fulfill is to have some latest posts, the count of the posts is not the key. There's no point having the coverpage full of text as the readability is much worse. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/10#issuecomment-66795215

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> 2. You don't understand me, different dpi/resolutions means your tweak only covered half of the cover on xperia x(+), just use the emulator to see what your changes do to all devices (like tablets), on jollaC 4 was fine, but on xperia x totally not (padding was reduced because why display empty space when ppl want content)
>
I do understand your point about different dpi/resolutions and that not all space is used. And it's not my "tweak" it was first feature implementation. On XA2 looked nice even though the screens are different. 
> I'm fine with text behind the reload icon, makes more sense and even fulfills some function
>
On the other hand you don't seem to understand my point. You're seemingly pushing some bad design to fix something that's not that relevant currently and need more tweaking as you have stated here as well. You might need to elaborate and concentrate on how you are expressing your things since your tweaking doesn't do the trick and your main argument is that it fulfills the function and makes more sense. 

Nevertheless, there's no point arguing with this any longer. Do what you got to do and tweak it as you wish.

**Comment by szopin** [comment]
> On XA2 looked nice even though the screens are different.
That's not good enough? 'On jolla C it looks nice' is not a good argument when on other devices it doesn't. 

>You're seemingly pushing some bad design to fix something that's not that relevant currently and need more tweaking as you have stated here as well.
Not really, I'm fine with content behind the reload icon as it is still readable and serves the purpose (more content), if anyone proposes a 'fix' that makes the area behind icon clean, fine, probably cleaner UI but content is lost, can't please everyone. Having a cover that has top third with content and bottom 2/3rds with nothing is definitely relevant btw, please test your pull requests thoroughly

**Comment by Moppa5** [comment]
> fine, probably cleaner UI but content is lost
>
Are you really kidding me? Do you want to put the whole viewer then to the coverpage? 
> please test your pull requests thoroughly
>
Not really only my job to review stuff as you already mentioned that "can't please everyone". The fact that I don't see 2/3rds with nothing as such a problem doesn't mean that I have only have to test thoroughly, this is not my repo and I'm not the one merging and reviewing the PRs. You request changes if you are not happy, you don't merge and start ranting afterwards about some stuff, surely there was the bug that needs to be fixed yet still. 

But never mind, good luck with that attitude and developing style.

**Comment by szopin** [comment]
> Are you really kidding me? Do you want to put the whole viewer then to the coverpage?

Where did I say that? I mentioned 'if someone makes the area behind reload icon clear', how did you get to 'whole viewer in coverpage'?

> Not really only my job to review stuff

Then please do not submit pull requests, if you can't be arsed to test what you submit then it's  a prototype level bullshit, I don't have time to review and test anyone's prototype, if you have something that is production ready then go ahead, if you know of bugs then please refrain from pulling the PR trigger, you can have fun in your fork all you want

**Pull request merged**
