### PR TITLE
fixes, adds

### PR DESCRIPTION
**Pull request by GNUuser**

### CODE REVIEW

**Comment by szopin** [comment]
It's conflicting, the artwork in About page is not the app icon btw, it's the old version of the icon by Hanibu (I want to keep it as I like it), most strings should already be translatable after the latest commits

**Comment by GNUuser** [comment]
ok, refresh i18n to send a es.ts

**Comment by GNUuser** [comment]
The icon in aboutPage  need remove it it's bad for design, and it's conflict with the main icon.

**Comment by szopin** [comment]
Not sure about the 'refresh i18n' part. The artwork in aboutpage stays, the poll on the forum is pretty close to 50-50 (17-14), so almost half of the people liked it

**Comment by GNUuser** [comment]
refresh i18n: like refresh all strings to translations folder to be updated.  To be honest I don't like the new icon very much, because this type of icon refers more to an IM app and not to an app forum, but the new icon is better than old and poorly designed.
I honestly don't know why people always do or follow what someone else does or thinks, but they never create a new, genuine metaphor.
dseight  tried to create a second icon to make a more forum icon but the metaphor was poor.

**Comment by szopin** [comment]
Updating from tools->external->linguist does only this:
```
Updating 'translations/harbour-sfos-forum-viewer-de.ts'...
    Found 34 source text(s) (0 new and 34 already existing)
Updating 'translations/harbour-sfos-forum-viewer-en.ts'...
    Found 34 source text(s) (0 new and 34 already existing)
```

Not sure how to add another language, don't see anything else in the UI, manually adding ...-es.ts in .pro generated a file with 'unfinished' everywhere, but it doesn't even contain (language="de_DE") part, does this one have to be done manually? If there is a simpler way pls let me know

**Comment by ichthyosaurus** [comment]
> Not sure how to add another language, don't see anything else in the UI, manually adding ...-es.ts in .pro generated a file with 'unfinished' everywhere, but it doesn't even contain (language="de_DE") part, does this one have to be done manually? If there is a simpler way pls let me know

It's fine how you're doing it. You can select the target language after opening the new file with QtLinguist for the first time.

> To be honest I don't like the new icon very much, because this type of icon refers more to an IM app and not to an app forum, but the new icon is better than old and poorly designed.
> I honestly don't know why people always do or follow what someone else does or thinks, but they never create a new, genuine metaphor balanced.
> dseight tried to create a second icon to make a more forum icon but the metaphor was poor.

@GNUuser do you have an idea for a better metaphor? I also think the new icon looks more like an IM app but I don't know what would be best for carrying the meaning of "forum"...

**Comment by szopin** [comment]
Thanks, es.ts generated and pushed

**Comment by GNUuser** [comment]
Yes i have a good think to a new icon. But I would like to create the metaphor then @dseight create the icon, i want keep @dseight as main icon designer.

**Pull request closed without merging**
