### PR TITLE
Support Subcategories

### PR DESCRIPTION
**Pull request by nephros**
Fixes: #61

### CODE REVIEW

**Comment by nephros** [comment]
instead of storing the parent ID, we could store the parent_slug and parent_name, that should make the display part a bit cleaner.

**Comment by nephros** [comment]
haven't tried posting, is the [`category`](https://github.com/szopin/harbour-sfos-forum-viewer/blob/master/qml/pages/FirstPage.qml#L63) valid for a post in a subcategory?

**Comment by szopin** [comment]
> haven't tried posting, is the [`category`](https://github.com/szopin/harbour-sfos-forum-viewer/blob/master/qml/pages/FirstPage.qml#L63) valid for a post in a subcategory?

I think subcategory id should work fine here, the docs aren't too exhaustive and say only:
category | integer Optional if creating a new topic, and ignored if creating a new post.
(though that is for admin api keys, but they usually match), so sub id should work as no mention of list (for category-.subcategory)

**Comment by szopin** [comment]
Thanks! Works great, credited you as 'nephros' let me know if you prefer some other way

**Comment by nephros** [comment]
> Thanks! Works great, credited you as 'nephros' let me know if you prefer some other way

That is fine, thank you!

**Pull request merged**
