### PR TITLE
Update harbour-sfos-forum-viewer-es.ts

### PR DESCRIPTION
**Pull request by GNUuser**
I confused. I do not know diference between LASTEST - TOP
What is TOP here?

### CODE REVIEW

**Comment by szopin** [comment]
Wait... wtf is es_GT?

**Comment by GNUuser** [comment]
Wait... why es_ES? I am not from spain to ES.

**Comment by szopin** [comment]
es_ES is what worked when I turned my language in my jollaC to espanol when you reported spanish is fucked... have you tested es_GT? Or are we gonna have another rampage in the next 25 minutes looking for bugs and fixes?

**Comment by GNUuser** [comment]
But why es_ES here when *.pro file is only es.ts ? So leave like this if not work i revert next commit.

**Comment by szopin** [comment]
es_ES is the language code!!! You shou;ld've chosen it when translating to spanish (unless ecuadorian spanish or bolivian I guess???)

**Comment by szopin** [comment]
-es.ts is just about some spanish... you can identify more than one, look at line 3:
language:es_ES
It could be es_bolivian, es_Colombian, es_Cuban...

**Comment by GNUuser** [comment]
> es_ES is the language code!!! You shou;ld've chosen it when translating to spanish (unless ecuadorian spanish or bolivian I guess???)

Yes is language code but only work if you to include in *.pro files. So leave like this. trust me = )

**Comment by szopin** [comment]
Dude, without it it would crash qtlinguist... but as you wish

**Comment by szopin** [comment]
Btw what the fuck is es_GT? Spanish gran turismo?

**Comment by GNUuser** [comment]
GT mean Fast car Furious =  ) i  am joking .
GT mean GuaTemala  like i  am from, a truly spanish speaker.

**Comment by szopin** [comment]
Ok, so... es_GT means Guatemala???

**Comment by szopin** [comment]
Can we get Kamala Harris on it?

**Review by szopin — CHANGES_REQUESTED** [review]
BAD, it needs to be es_ES

**Comment by GNUuser** [comment]
is reverted

**Comment by szopin** [comment]
> 
> 
> is reverted

why would you reverte it?

**Comment by szopin** [comment]
You can't even ABC

**Comment by szopin** [comment]
I mean kamala harris is 2.5

**Comment by szopin** [comment]
Ok, sorry it was an accident, we don't want to close it

**Comment by szopin** [comment]
Like seriously

**Comment by GNUuser** [comment]
merget it

**Comment by GNUuser** [comment]
merge the code.

**Comment by szopin** [comment]
wtf

**Pull request merged**
