### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by mentaljam**
This PR mainly affects data loading but also introduce some minor optimizations of property bindings.

### CODE REVIEW

**Comment by szopin** [comment]
Can you pls provide an overview of changes? It's so many it's going to take me a huge while to look through it

**Comment by mentaljam** [comment]
I tried to provide descriptions in commits. Every commit affects one file (except the 30acc23) to make it easy to review changes.

In general terms:

- Use single property to store forum URL: `application.source` in [qml/harbour-sfos-forum-viewer.qml](https://github.com/szopin/harbour-sfos-forum-viewer/blob/e934665d928f89e4994afc47ab9ddf99f10ea4cd/qml/harbour-sfos-forum-viewer.qml#L46)
- Refactor code to exclude duplicated parts
- Optimize accessing properties on data fetching as in 3dd0761:

instead of multiple accessing in for loop like
```qml
data.topic_list.topics[i]["prop_name"]
```

use
```qml
var topics = data.topic_list.topics;
for (var i=0;i<topics_length;i++) {
  var topic = topics[i];
  ...
  application.latest.append({title: topic.title, posts_count: topic.posts_count})
}
```

**Comment by szopin** [comment]
> Use single property to store forum URL
Hell fuck yeah, I had a pre-release shit on my phone since 0.6 and it just never made it, awesome

> Refactor code to exclude duplicated parts
> Optimize accessing properties on data fetching as in
I love it and at the same time... refactor can mean 5 thousand things are we sure we're on the same page?

**Comment by mentaljam** [comment]
> are we sure we're on the same page?

I tested every commit and didn't notice any regression. But you know, it does not mean anything))

**Comment by szopin** [comment]
> 
> 
> > are we sure we're on the same page?
> 
> I tested every commit and didn't notice any regression. But you know, it does not mean anything))

Awesome! Thanks!

**Comment by szopin** [comment]
Do you prefer Petr Tsymbarovich or mentaljam as credit in aboutPage???

**Comment by mentaljam** [comment]
mentaljam

**Comment by szopin** [comment]
Thanks man, will take me a few evenings to grasp all you did but it's all out in 0.8.5, great stuff

**Pull request merged**
