### PR TITLE
italian translation added

### PR DESCRIPTION
**Pull request by legacychimera247**
Hello, i just added the italian translation :D

### CODE REVIEW

**Comment by szopin** [comment]
Thanks!

**Comment by legacychimera247** [comment]
Weirdly enough the app is still in english, any hint?

**Comment by szopin** [comment]
Oh no... I think for new language I need to click one option in sdk I forgot

On Friday, 9 August 2024, legacychimera247 wrote:
> Weirdly enough the app is still in english, any hint?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/72#issuecomment-2277438148
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Should be fixed in 1.9.7

Il Venerdì 9 agosto 2024, legacychimera247 scrive:
> Weirdly enough the app is still in english, any hint?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/72#issuecomment-2277438148
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by legacychimera247** [comment]
Fixed it, thank you

**Pull request merged**
