### PR TITLE
Update harbour-sfos-forum-viewer-es.ts

### PR DESCRIPTION
**Pull request by GNUuser**
May be work like this way.

### CODE REVIEW

**Comment by GNUuser** [comment]
check now

**Comment by szopin** [comment]
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.

It ate the second form... Are you sure you don't need to add language=es_ES?

**Comment by szopin** [comment]
Change line 3 to:
   <TS version="2.1" language="es_ES">

Then it passes correctly, let me know if it actually displays in spanish as no way to test in emulator

**Comment by szopin** [comment]
Tested on phone, 0.8.2.1 works with spanish locale

**Pull request merged**
