### PR TITLE
Show solved and new

### PR DESCRIPTION
**Pull request by ichthyosaurus**
- Save which thread the user has read and highlight threads with new messages
-  Scroll to the last read post if there are new posts in an already visited thread
- Mark solved threads

### CODE REVIEW

**Comment by szopin** [comment]
Nice, wonder how much storage this will actually take, but probably a user executed cleanup button will suffice if someone worries about that (or ofa possible slowdown?). Btw is this not conflicting with the scroll to post from search results? Can't test right now, will get to the SDK only in the evening

**Comment by ichthyosaurus** [comment]
- storage: it shouldn't take much storage. It stores one integer value per opened thread with an integer key in dconf. Threads the user never clicks on are not saved. Yes, a cleanup button might be enough.
- performance: it shouldn't have a big impact on performance. It reads one value per thread on one page, that's normally 20 threads.
- search feature: in my tests everything worked fine...

**Comment by ichthyosaurus** [comment]
It might be nice having the same on the cover (but that's out of scope for the moment).

**Comment by szopin** [comment]
Awesome, thanks!

On Wednesday, 26 August 2020, ichthyosaurus wrote:
> - storage: it shouldn't take much storage. It stores one integer value per opened thread with an integer key in dconf. Threads the user never clicks on are not saved. Yes, a cleanup button might be enough.
> - performance: it shouldn't have a big impact on performance. It reads one value per thread on one page, that's normally 20 threads.
> - search feature: in my tests everything worked fine...
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/39#issuecomment-68101144

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Works perfect, just curious if maybe scroll to new post wouldn't make more sense? At least in my limited testing having to scroll to the the actually unread post seems a bit superfluous (ideally in the future a setting would give all 3 options I guess, but that's more of 1.0 feature), it's the content you want to read if you follow a thread?

On Wednesday, 26 August 2020, ichthyosaurus wrote:
> - storage: it shouldn't take much storage. It stores one integer value per opened thread with an integer key in dconf. Threads the user never clicks on are not saved. Yes, a cleanup button might be enough.
> - performance: it shouldn't have a big impact on performance. It reads one value per thread on one page, that's normally 20 threads.
> - search feature: in my tests everything worked fine...
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/39#issuecomment-68101144

-- 
Sent from my Jolla

**Comment by ichthyosaurus** [comment]
Sure, would be more sensible! I just didn't have the time to implement it, so I thought it's better to have it half than not at all.

**Comment by szopin** [comment]
I think just  a +1 should do it (will check when I get home, was just curious if maybe there's some reasoning behind it I missed)

On Friday, 28 August 2020, ichthyosaurus wrote:
> Sure, would be more sensible! I just didn't have the time to implement it, so I thought it's better to have it half than not at all.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/pull/39#issuecomment-68288574

-- 
Sent from my Jolla

**Pull request merged**
