### PR TITLE
Update harbour-sfos-forum-viewer.desktop

### PR DESCRIPTION
**Pull request by GNUuser**
Revamping main name, was too big.

### CODE REVIEW

**Comment by szopin** [comment]
Hey, thanks for bringing this up, just not sure about SForum... 'SFOS Forum' would work for the desktop name I guess (at least on Jolla C seems to fit) and SFOS Foro I guess for spanish locale? Could you change that and will merge it, thanks!

**Comment by szopin** [comment]
Oh also please let me know which nick you prefer to be credited as (GNUuser or carlosgonz or...)

**Comment by GNUuser** [comment]
carlosgonz

**Comment by GNUuser** [comment]
I really recommend the short phrare " SForum " It is  cool to reuse the word " F " Fish Forum at same time, however you have the real decision.

**Comment by szopin** [comment]
Not really sure about that... (might be too close to a word in my native language which is causing that, not sure) How about... for now change it to SFOS Forum/Foro... I'll merge this for now as it will close the issue of too long dektop-name and you open an issue/suggestion of name change (or the dektop-name change at least changing the whole harbour-sfos-... is a whole different can of worms) to SForum? If we get few more contributors or users OKaying that then sure

**Comment by GNUuser** [comment]
OK I will change it to the generic name "  SFOS Forum "

**Pull request merged**
